server:
  port: 8080

spring:
# H2 Setting
#  h2:
#    console:
#      enabled: true
#      path: /h2
# Datasource Setting
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_UPPER=false;INIT=RUNSCRIPT FROM 'data-h2.sql'
#    username: sa
#    password: 
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/order?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
## Hibernate
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
# Eventuate Setting
eventuate:
  database:
    schema: eventuate

eventuatelocal:
  kafka:
    bootstrap:
      servers: localhost:9092